INCLUDE "IO.h"

DISPLAY_ENABLE = 0x1
DISPLAY_PRESENT = 0x2

DISPLAY_FORMAT_RGBA8 = 0x0
DISPLAY_FORMAT_RGB8 = 0x1
DISPLAY_FORMAT_RGBA4 = 0x2
DISPLAY_FORMAT_RGB565 = 0x3
DISPLAY_FORMAT_RGBA5551 = 0x4


MACRO DISPLAY_FORMAT_CREATE Width, Height, Fmt{ (Width & 0x3FFF) | ((Height & 0x3FFF) << 14) | ((Fmt & 0x1F) << 28) }

EnableDisplay:
	IMM32 R0, DISPLAY_CTR
	MOV R1, DISPLAY_ENABLE
	ST R1, [R0]
	RET

; R0 Buffer Address
; R1 Display Format, see DISPLAY_FORMAT_CREATE
SetDisplayBuffer:
	IMM32 R2, DISPLAY_FORMAT
	ST R1, [R2]
	IMM32 R2, DISPLAY_BUFFER
	ST R0, [R2]
	RET

PresentDisplay:
	IMM32 R0, DISPLAY_CTR
	LD R1, [R0]
	OR R1, R1, DISPLAY_PRESENT
	ST R1, [R0]
	RET
