IO_BASE = 0x10000000

DMA_BASE =      IO_BASE | 0x00000;
IRQ_BASE =      IO_BASE | 0x01000;
PAD_BASE =      IO_BASE | 0x02000;
DEBUG_BASE =    IO_BASE | 0x04000;
GU_BASE =       IO_BASE | 0x10000;

; DMA
DMA_RAM_CHANNEL =   DMA_BASE | 0x000;
DMA_GU_CHANNEL =    DMA_BASE | 0x010;
DMA_EMD_CHANNEL =   DMA_BASE | 0x020;
DMA_SPU_CHANNEL =   DMA_BASE | 0x030;

DMA_RAM_CHANNEL_CTR = DMA_RAM_CHANNEL | 0x0
DMA_RAM_CHANNEL_SRC = DMA_RAM_CHANNEL | 0x4
DMA_RAM_CHANNEL_DST = DMA_RAM_CHANNEL | 0x8
DMA_RAM_CHANNEL_CNT = DMA_RAM_CHANNEL | 0xC

DMA_GU_CHANNEL_CTR = DMA_GU_CHANNEL | 0x0
DMA_GU_CHANNEL_SRC = DMA_GU_CHANNEL | 0x4
DMA_GU_CHANNEL_DST = DMA_GU_CHANNEL | 0x8
DMA_GU_CHANNEL_CNT = DMA_GU_CHANNEL | 0xC

DMA_EMD_CHANNEL_CTR = DMA_EMD_CHANNEL | 0x0
DMA_EMD_CHANNEL_SRC = DMA_EMD_CHANNEL | 0x4
DMA_EMD_CHANNEL_DST = DMA_EMD_CHANNEL | 0x8
DMA_EMD_CHANNEL_CNT = DMA_EMD_CHANNEL | 0xC

DMA_SPU_CHANNEL_CTR = DMA_SPU_CHANNEL | 0x0
DMA_SPU_CHANNEL_SRC = DMA_SPU_CHANNEL | 0x4
DMA_SPU_CHANNEL_DST = DMA_SPU_CHANNEL | 0x8
DMA_SPU_CHANNEL_CNT = DMA_SPU_CHANNEL | 0xC

DMA_ENABLE_MASK =   DMA_BASE | 0x100;
DMA_IRQ_MASK =      DMA_BASE | 0x104;
DMA_PRIORITY_MASK = DMA_BASE | 0x108;
DMA_WAIT_ON_MASK =  DMA_BASE | 0x10C;

; IRQ
IRQ_STATUS =        IRQ_BASE | 0x00;
IRQ_ENABLE_MASK =   IRQ_BASE | 0x04;

; PAD
IO_PAD_MAIN_BUTTONS = PAD_BASE | 0x000
IO_PAD_MAIN_STICKS = PAD_BASE | 0x004
IO_PAD_MAIN_STATUS = PAD_BASE | 0x008
IO_PAD_MAIN_SYNC_BUFFER = PAD_BASE | 0x00C

; DEBUG
DEBUG_CTR =         DEBUG_BASE | 0x000
DEBUG_IRQ_MASK =    DEBUG_BASE | 0x004
DEBUG_FIFO =        DEBUG_BASE | 0x008

; GU
GU_IRQ_MASK =   GU_BASE | 0x0000
GU_STATUS =     GU_BASE | 0x0004
GU_CTR =        GU_BASE | 0x0008
GU_ID =         GU_BASE | 0x000C

GU_DISPLAYADDR =    GU_BASE | 0x0010
GU_DISPLAYFMT =     GU_BASE | 0x0014

GU_TRANSFER_INADDR =    GU_BASE | 0x0100
GU_TRANSFER_INFMT =     GU_BASE | 0x0104
GU_TRANSFER_OUTADDR =   GU_BASE | 0x0108
GU_TRANSFER_OUTFMT =    GU_BASE | 0x010C

GU_TRANSFER_COUNT =     GU_BASE | 0x0110
GU_TRANSFER_CTR =       GU_BASE | 0x0110
GU_TRANSFER_IRQ_MASK =  GU_BASE | 0x0110
GU_TRANSFER_ID =        GU_BASE | 0x0110


GU_QUEUE_CMD =  GU_BASE | 0x0120
GU_QUEUE_ADDR = GU_BASE | 0x0124
GU_QUEUE_CTR =  GU_BASE | 0x0128

